classes={
    'bike':{
        'classCode':1,
        'info':[
            {'videoName':'Pedestrain','trajectoryName':4}
        ]
    },
    'boats':{
        'classCode':2,
        'info':[
            {'videoName':'boats','trajectoryName':1}
        ]
    },
    'canoe':{
        'classCode':3,
        'info':[
            {'videoName':'canoe','trajectoryName':1}
        ]
    },
    'car':{
        'classCode':4,
        'info':[
            {'videoName':'blizzard','trajectoryName':1},
            {'videoName':'blizzard','trajectoryName':2},
            {'videoName':'blizzard','trajectoryName':3},
            {'videoName':'blizzard','trajectoryName':4},
            {'videoName':'blizzard','trajectoryName':5},
            {'videoName':'blizzard','trajectoryName':6},
            {'videoName':'blizzard','trajectoryName':7},
            {'videoName':'boulevard','trajectoryName':3},
            {'videoName':'fall1','trajectoryName':1},
            {'videoName':'fall3','trajectoryName':1},
            {'videoName':'fall4','trajectoryName':2},
            {'videoName':'fall5','trajectoryName':2}
        ]
    },
    'human':{
        'classCode':5,
        'info':[
            {'videoName':'Pedestrain','trajectoryName':1},
            {'videoName':'Pedestrain','trajectoryName':2},
            {'videoName':'Pedestrain','trajectoryName':3},
            {'videoName':'fall5','trajectoryName':1},
            {'videoName':'pets2006','trajectoryName':1},
            {'videoName':'pets2006','trajectoryName':2},
            {'videoName':'pets2006','trajectoryName':3},
            {'videoName':'pets2006','trajectoryName':4},
            {'videoName':'pets2006','trajectoryName':5},
            {'videoName':'skating','trajectoryName':1},
            {'videoName':'skating','trajectoryName':2},
            {'videoName':'skating','trajectoryName':3}
        ]
    },
    'noise':{
        'classCode':6,
        'info':[
            {'videoName':'fall5','trajectoryName':3}
        ]
    },
    'pickup':{
        'classCode':7,
        'info':[
            {'videoName':'fall2','trajectoryName':1}
        ]
    },
    'truck':{
        'classCode':8,
        'info':[
            {'videoName':'boulevard','trajectoryName':2},
            {'videoName':'fall4','trajectoryName':1}
        ]
    },
    'van':{
        'classCode':9,
        'info':[
            {'videoName':'boulevard','trajectoryName':1}
        ]
    },
}